### PR TITLE
Lots of minor fixes

### LINKED ISSUE #33: Define better type hints by substituting the any types
There are lots of types that could be more precisely defined. Doing this better typing will help with supporting the software in the future

### LINKED ISSUE #37: There is an additional row of cells for both the rows and columns
Must be an off by one error somewhere, they're not clickable.

### PR DESCRIPTION
**Pull request by JackWilb**
Fixes a lot of minor issues:
- Tooltip positioning
- D3 does not plot outside the SVG (I think this was causing #37 so this closes #37)
- Adds better typing (closes #33)
- Refactors the hovering logic

Partial fix for #59.

These fixes simplify some of the hovering logic which will be important for debugging the slow highlighting

### CODE REVIEW

File: src/components/AdjMatrix/AdjMatrix.vue [hunk 1]
```diff
@@ -85,15 +85,15 @@ export default Vue.extend({
     // Size the svgs
     this.matrix = d3
       .select(this.$refs.matrix)
-      .attr('width', this.visDimensions.width * 0.75 - 30)
+      .attr('width', this.visDimensions.width * 0.75)
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrix.vue:88]: I think it would make sense to refactor all of these values into computed props with a descriptive name (like `matrixWidth` or something like that).

File: src/components/AdjMatrix/AdjMatrixMethods.ts [hunk 2]
```diff
@@ -41,13 +32,10 @@ export class View {
   private colMargin: number = 5;
   private visDimensions: Dimensions;
   private provenance: any;
-  private idMap: { [key: string]: number};
-  private hoverRow: {} = {};
-  private hoverCol: {} = {};
+  private idMap: { [key: string]: number };
   private isMultiEdge: any;
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrixMethods.ts:40]: `isMultiEdge` sounds like a `boolean`.

File: src/components/AdjMatrix/AdjMatrixMethods.ts [hunk 3]
```diff
@@ -82,20 +71,13 @@ export class View {
...
-   * @param  data [description]
-   * @return      [description]
-   */
-  public loadData(): void {
     // Kick off the rendering
     this.initializeEdges();
     this.initializeAttributes();
   }
 
+
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrixMethods.ts:84]:
```suggestion

```

File: src/components/AdjMatrix/AdjMatrixMethods.ts [hunk 4]
```diff
@@ -942,15 +896,15 @@ export class View {
...
+  private nodeClick(node: Node, search: boolean = false): void {
   const previousState = this.getApplicationState();
   let clicked = previousState.clicked;
   const wasSelected = this.isSelected(node);
 
   if (wasSelected) {
     clicked = clicked.filter((s: any) => s !== node.id);
   } else {
-    clicked.push(node.id);
+    clicked.push(node.id as never);
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrixMethods.ts:760]: What does this mean? (I haven't run across the `never` type too much.)

File: src/components/AdjMatrix/AdjMatrixMethods.ts [hunk 5]
```diff
@@ -1232,66 +1186,35 @@ export class View {
...
-            }
-          });
+    // Find max value of z
+    this.matrix.forEach((row: Cell[]) => {
+      row.forEach((cell: Cell) => {
+        if (cell.z > this.maxNumConnections) {
+          this.maxNumConnections = cell.z;
+        }
       });
+    });
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrixMethods.ts:1020]: There is probably a more functional way to extract this max value. It may not be worthwhile to convert it over to that style though. Let me know if you want to discuss it.

File: src/components/AdjMatrix/AdjMatrixMethods.ts [hunk 6]
```diff
@@ -625,142 +585,36 @@ export class View {
...
+      for (const neighborNode of this.columnSelectedNodes[node]) {
+        cssSelector += `
+        [id="attrRow${neighborNode}"],[id="topoRow${neighborNode}"],[id="nodeLabelRow${neighborNode},"]
+        `;
       }
     }
-    // remove last comma
+
+    // Remove last comma
     cssSelector = cssSelector.substring(0, cssSelector.length - 1);
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrixMethods.ts]: This feels pretty brittle. You may want to consider generating an array of strings to hold the individual selectors, then calling `join()` on it at the end.

File: src/components/AdjMatrix/AdjMatrix.vue [hunk 7]
```diff
@@ -91,9 +91,9 @@ export default Vue.extend({
 
     this.attributes = d3
       .select(this.$refs.attributes)
-      .attr('width', this.visDimensions.width * 0.25)
+      .attr('width', this.visDimensions.width * 0.25 - 15) // -15 for the scroll bar
       .attr('height', this.visDimensions.height)
-      .attr('viewBox', `0 0 ${this.visDimensions.width * 0.25} ${this.visDimensions.height}`);
+      .attr('viewBox', `0 0 ${this.visDimensions.width * 0.25 - 15} ${this.visDimensions.height}`);
```
Comment (waxlamp) [inline src/components/AdjMatrix/AdjMatrix.vue]: I would recommend keeping the `15` in a `const` variable (or even a computed prop, but that might be too extreme).

File: src/components/AdjMatrix/AdjMatrixMethods.ts (hunk 4 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrixMethods.ts:760]: This means that the clicked array was never defined. I just added `clicked: string[] = previousState.clicked;` and now I can pass it without a type conversion

File: src/components/AdjMatrix/AdjMatrixMethods.ts (hunk 2 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrixMethods.ts:40]: Fixed on my new branch at 006792d

File: src/components/AdjMatrix/AdjMatrixMethods.ts (hunk 3 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrixMethods.ts:84]: My preference is 2 spaces between function blocks. Fixed on my new branch at 006792d

File: src/components/AdjMatrix/AdjMatrixMethods.ts (hunk 4 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrixMethods.ts:760]: Fixed on my new branch at 006792d

File: src/components/AdjMatrix/AdjMatrix.vue (hunk 1 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrix.vue:88]: I refactored this on my new branch at 8774837

File: src/components/AdjMatrix/AdjMatrix.vue (hunk 7 above)
Comment (JackWilb) [reply src/components/AdjMatrix/AdjMatrix.vue]: I didn't store this in a const because with the refactoring in 8774837, it's only used in one place

File: src/components/AdjMatrix/AdjMatrixMethods.ts (hunk 5 above)
Comment (waxlamp) [reply src/components/AdjMatrix/AdjMatrixMethods.ts:1020]: No, it's more just a style thing. I find that functional thinking leads to better code, both in terms of readability and reasoning about it if something goes wrong. Since this works just fine, there's no rush to change it, more just something to think about.
